import Board from "@/components/dnd/board/Board";
import { Button } from "@/components/ui/button";
import BackButton from "@/components/utils/BackButton";
import { trpc } from "@/lib/trpc";
import { NextPage } from "next";
import Head from "next/head";
import { useRouter } from "next/router";

const BoardView: NextPage = () => {
  const router = useRouter();
  const boardId = router.query.boardId as string;

  const { data: board, refetch: refetchLanes } =
    trpc.board.getBoardById.useQuery(
      {
        boardId,
      },
      { enabled: !!boardId }
    );

  return (
    <>
      <Head>
        <title>{board?.Name}</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="relative flex h-[calc(100vh-40px)] flex-col items-center overflow-x-hidden pt-1">
        <div className="flex w-full justify-between px-1 sm:justify-evenly">
          <BackButton />
          <h2>Board: {board?.Name}</h2>
          <div>Settings</div>
        </div>
        {board?.Lanes ? (
          <Board
            initial={board.Lanes}
            boardId={boardId}
            containerHeight={500}
            useClone={false}
            withScrollableColumns={false}
            refetchLanes={refetchLanes}
            isCombineEnabled={false}
          />
        ) : (
          <div>loading</div>
        )}
      </main>
    </>
  );
};

export default BoardView;
