import BoardsView from "@/components/BoardsView";
import SideView from "@/components/SideView";
import MainGrid from "@/components/utils/MainGrid";
import { trpc } from "@/lib/trpc";
import { NextPage } from "next";
import Head from "next/head";

const Boards: NextPage = () => {
  const { data: workspaces } = trpc.workspace.getWorkspacesByUser.useQuery();
  return (
    <>
      <Head>
        <title>Dashboard</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="m-2 flex justify-center overflow-hidden">
        <MainGrid>
          <SideView workspaces={workspaces} />
          <BoardsView workspaces={workspaces} />
        </MainGrid>
      </main>
    </>
  );
};

export default Boards;
